"""event table

Revision ID: b06325670d6a
Revises: 985f5c5d9c9a
Create Date: 2020-09-24 23:57:24.925281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06325670d6a'
down_revision = '985f5c5d9c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('theme', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_end'), 'event', ['end'], unique=False)
    op.create_index(op.f('ix_event_start'), 'event', ['start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_start'), table_name='event')
    op.drop_index(op.f('ix_event_end'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
