"""empty message

Revision ID: c5d3375a4992
Revises: b06325670d6a
Create Date: 2020-09-27 13:58:01.317343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5d3375a4992'
down_revision = 'b06325670d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('event', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event', 'end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
